<?php

namespace app\controllers;

use app\models\TestModel;
use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;

class SiteController extends Controller
{
    // de aici schimb layoutul din main in base
//    public $layout='base';
//    public $enableCsrfValidation=false;
    public $layput='main';
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::class,
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::class,
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    public function beforeAction($action)
    {
//        if($action->id==="index")
//        {
//            $this->layout='admin';
//            $this->enableCsrfValidation=false;
//        }

//        if($action->id==="login")
//        {
////            $this->enableCsrfValidation=false;
//        }

//        echo '<prev>';
//        var_dump($action);
//        echo '</prev>';

        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

//    public function afterAction($action, $result)
//    {
//        echo '<prev>';
//        var_dump($result);
//        echo '</prev>';
//        return parent::afterAction($action, $result); // TODO: Change the autogenerated stub
//    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
//        echo '<prev> . <br><br><br>';
//        var_dump(Yii::$app->test->hello());
//        echo '</prev>';


//        echo '<prev>';
//        var_dump(Yii::$app->assetManager);
//        echo '</prev>';
        return $this->render('index');
    }



    /**
     * Login action.
     *
     * @return Response|string
     */
    public function actionLogin()
    {
        //cand apelez
        $this->layout="login";
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        }

        $model->password = '';
        return $this->render('login', [
            'model' => $model,
        ]);
    }

    /**
     * Logout action.
     *
     * @return Response
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Displays contact page.
     *
     * @return Response|string
     */
    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['adminEmail'])) {
            Yii::$app->session->setFlash('contactFormSubmitted');

            return $this->refresh();
        }
        return $this->render('contact', [
            'model' => $model,
        ]);
    }

    /**
     * Displays about page.
     *
     * @return string
     */
    public function actionAbout()
    {
        return $this->render('about');
    }

    public function actionTest()
    {
        $test=new TestModel();
////        $test->name='John';
//        echo $test['name'];
//        $test->surname='john@example.com';
//        $test->myAge=30;

        $test= new TestModel();

        $post=[
            'name'=>'Andrei',
            'surname'=>'andreisimionescu@leviatan',
            'email'=>'andreisimionescu@leviatan',
            'myAge'=>23,
        ];

        $test->attributes=$post;

        echo '<prev><br>';

        foreach ($test as $attr=>$valuess){
            echo $test->getAttributeLabel($attr).'='.$valuess.'<br>';
        }
        if($test->validate())
        {
            echo 'Ok';
        }
        else
        {
            echo 'Error';
        }

//        echo '<prev>';
//        var_dump($test->getAttributeLabel('surname'));
//        echo '<prev>';
    }

    public function actionHello($message)
    {
        return $this->render('hello',[
            'msg'=>$message
        ]);
    }

    public function actionRequest($id)
    {
//        echo isset($_GET['id']) ? $_GET['id']:null;
//        echo Yii::$app->request->get('id');

        //date din url
        $get=Yii::$app->request->get();
        echo '<prev>';
        var_dump($get);
        echo '<prev>';

        //pentru post

//        $post=Yii::$app->request->post('name','Andrei');
//        echo '<prev>';
//        var_dump($post);
//        echo '<prev>';

        //pentru put
        echo '<prev>';
        var_dump($id);
        var_dump($post=Yii::$app->request->getBodyParams());
        echo '</prev>';

        //imprima tot

        echo '<prev>';
        var_dump(Yii::$app->request->get());
        echo '</prev>';

        //

        $req=Yii::$app->request;

        echo '<prev>';
        var_dump($req->userAgent);
        echo '</prev>';
    }

    public function actionResponse()
    {

        //
//        $response=Yii::$app->response;
//        $response->statusCode=500;
//        $response->content="Hello From Andrei";

        //
        Yii::$app->response->format=Response::FORMAT_JSON;

        return [
            'name'=>'Zura',
            'surname'=>'Something'
        ];
    }

}
